<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Location;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $locations = [
            [
                'name' => 'Beauty Salon Downtown',
                'code' => 'SF001',
                'description' => 'Our flagship location in the heart of downtown San Francisco',
                'address' => '123 Market Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94102',
                'country' => 'US',
                'latitude' => 37.7749,
                'longitude' => -122.4194,
                'phone' => '(555) 123-4567',
                'email' => 'downtown@beautysalon.com',
                'website' => 'https://beautysalon.com',
                'business_hours' => [
                    'monday' => ['open' => '09:00', 'close' => '19:00'],
                    'tuesday' => ['open' => '09:00', 'close' => '19:00'],
                    'wednesday' => ['open' => '09:00', 'close' => '19:00'],
                    'thursday' => ['open' => '09:00', 'close' => '19:00'],
                    'friday' => ['open' => '09:00', 'close' => '19:00'],
                    'saturday' => ['open' => '10:00', 'close' => '18:00'],
                    'sunday' => ['open' => '10:00', 'close' => '18:00'],
                ],
                'amenities' => [
                    'Free WiFi',
                    'Parking Available',
                    'Wheelchair Accessible',
                    'Private Treatment Rooms',
                    'Refreshment Station',
                ],
                'timezone' => 'America/Los_Angeles',
                'tax_rate' => 0.0875,
                'currency' => 'USD',
                'is_active' => true,
                'is_headquarters' => true,
                'max_staff' => 15,
                'max_clients_per_day' => 100,
                'settings' => [
                    'booking_advance_days' => 30,
                    'cancellation_hours' => 24,
                    'no_show_fee' => 25.00,
                    'loyalty_points_multiplier' => 1.0,
                ],
            ],
            [
                'name' => 'Beauty Salon Marina',
                'code' => 'SF002',
                'description' => 'Upscale location in the Marina district with ocean views',
                'address' => '456 Chestnut Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94123',
                'country' => 'US',
                'latitude' => 37.8024,
                'longitude' => -122.4481,
                'phone' => '(555) 234-5678',
                'email' => 'marina@beautysalon.com',
                'website' => 'https://beautysalon.com',
                'business_hours' => [
                    'monday' => ['open' => '09:00', 'close' => '19:00'],
                    'tuesday' => ['open' => '09:00', 'close' => '19:00'],
                    'wednesday' => ['open' => '09:00', 'close' => '19:00'],
                    'thursday' => ['open' => '09:00', 'close' => '19:00'],
                    'friday' => ['open' => '09:00', 'close' => '19:00'],
                    'saturday' => ['open' => '10:00', 'close' => '18:00'],
                    'sunday' => ['open' => '10:00', 'close' => '18:00'],
                ],
                'amenities' => [
                    'Free WiFi',
                    'Valet Parking',
                    'Ocean Views',
                    'Luxury Treatment Rooms',
                    'Champagne Service',
                    'Wheelchair Accessible',
                ],
                'timezone' => 'America/Los_Angeles',
                'tax_rate' => 0.0875,
                'currency' => 'USD',
                'is_active' => true,
                'is_headquarters' => false,
                'max_staff' => 12,
                'max_clients_per_day' => 80,
                'settings' => [
                    'booking_advance_days' => 45,
                    'cancellation_hours' => 48,
                    'no_show_fee' => 50.00,
                    'loyalty_points_multiplier' => 1.5,
                ],
            ],
            [
                'name' => 'Beauty Salon Sunset',
                'code' => 'SF003',
                'description' => 'Community-focused location in the Sunset district',
                'address' => '789 Irving Street',
                'city' => 'San Francisco',
                'state' => 'CA',
                'postal_code' => '94122',
                'country' => 'US',
                'latitude' => 37.7599,
                'longitude' => -122.4665,
                'phone' => '(555) 345-6789',
                'email' => 'sunset@beautysalon.com',
                'website' => 'https://beautysalon.com',
                'business_hours' => [
                    'monday' => ['open' => '10:00', 'close' => '18:00'],
                    'tuesday' => ['open' => '10:00', 'close' => '18:00'],
                    'wednesday' => ['open' => '10:00', 'close' => '18:00'],
                    'thursday' => ['open' => '10:00', 'close' => '18:00'],
                    'friday' => ['open' => '10:00', 'close' => '18:00'],
                    'saturday' => ['open' => '09:00', 'close' => '17:00'],
                    'sunday' => ['closed' => true],
                ],
                'amenities' => [
                    'Free WiFi',
                    'Street Parking',
                    'Family-Friendly',
                    'Community Room',
                    'Wheelchair Accessible',
                ],
                'timezone' => 'America/Los_Angeles',
                'tax_rate' => 0.0875,
                'currency' => 'USD',
                'is_active' => true,
                'is_headquarters' => false,
                'max_staff' => 8,
                'max_clients_per_day' => 60,
                'settings' => [
                    'booking_advance_days' => 21,
                    'cancellation_hours' => 12,
                    'no_show_fee' => 15.00,
                    'loyalty_points_multiplier' => 1.0,
                ],
            ],
            [
                'name' => 'Beauty Salon Los Angeles',
                'code' => 'LA001',
                'description' => 'Our first location in Los Angeles, Beverly Hills area',
                'address' => '321 Rodeo Drive',
                'city' => 'Beverly Hills',
                'state' => 'CA',
                'postal_code' => '90210',
                'country' => 'US',
                'latitude' => 34.0736,
                'longitude' => -118.4004,
                'phone' => '(555) 456-7890',
                'email' => 'beverlyhills@beautysalon.com',
                'website' => 'https://beautysalon.com',
                'business_hours' => [
                    'monday' => ['open' => '09:00', 'close' => '20:00'],
                    'tuesday' => ['open' => '09:00', 'close' => '20:00'],
                    'wednesday' => ['open' => '09:00', 'close' => '20:00'],
                    'thursday' => ['open' => '09:00', 'close' => '20:00'],
                    'friday' => ['open' => '09:00', 'close' => '20:00'],
                    'saturday' => ['open' => '10:00', 'close' => '19:00'],
                    'sunday' => ['open' => '11:00', 'close' => '18:00'],
                ],
                'amenities' => [
                    'Free WiFi',
                    'Valet Parking',
                    'Celebrity Suite',
                    'Private Entrance',
                    'Luxury Amenities',
                    'Wheelchair Accessible',
                    'Concierge Service',
                ],
                'timezone' => 'America/Los_Angeles',
                'tax_rate' => 0.10,
                'currency' => 'USD',
                'is_active' => true,
                'is_headquarters' => false,
                'max_staff' => 20,
                'max_clients_per_day' => 120,
                'settings' => [
                    'booking_advance_days' => 60,
                    'cancellation_hours' => 72,
                    'no_show_fee' => 100.00,
                    'loyalty_points_multiplier' => 2.0,
                ],
            ],
            [
                'name' => 'Beauty Salon San Jose',
                'code' => 'SJ001',
                'description' => 'Tech-focused location in the heart of Silicon Valley',
                'address' => '654 Santana Row',
                'city' => 'San Jose',
                'state' => 'CA',
                'postal_code' => '95128',
                'country' => 'US',
                'latitude' => 37.3205,
                'longitude' => -121.9487,
                'phone' => '(555) 567-8901',
                'email' => 'sanjose@beautysalon.com',
                'website' => 'https://beautysalon.com',
                'business_hours' => [
                    'monday' => ['open' => '08:00', 'close' => '19:00'],
                    'tuesday' => ['open' => '08:00', 'close' => '19:00'],
                    'wednesday' => ['open' => '08:00', 'close' => '19:00'],
                    'thursday' => ['open' => '08:00', 'close' => '19:00'],
                    'friday' => ['open' => '08:00', 'close' => '19:00'],
                    'saturday' => ['open' => '09:00', 'close' => '18:00'],
                    'sunday' => ['open' => '10:00', 'close' => '17:00'],
                ],
                'amenities' => [
                    'Free WiFi',
                    'Underground Parking',
                    'Tech Lounge',
                    'Charging Stations',
                    'Quiet Zones',
                    'Wheelchair Accessible',
                    'Mobile App Integration',
                ],
                'timezone' => 'America/Los_Angeles',
                'tax_rate' => 0.0925,
                'currency' => 'USD',
                'is_active' => true,
                'is_headquarters' => false,
                'max_staff' => 10,
                'max_clients_per_day' => 75,
                'settings' => [
                    'booking_advance_days' => 14,
                    'cancellation_hours' => 6,
                    'no_show_fee' => 20.00,
                    'loyalty_points_multiplier' => 1.2,
                ],
            ],
        ];

        foreach ($locations as $locationData) {
            Location::create($locationData);
        }
    }
}